---
version: '3'
services:
    deploy:
        build:
            context: ./deploy
            dockerfile: Deploy.Dockerfile
        volumes:
            - /home/devops_learning/employment_7/tmp://home/java-war-project/target
    prod:
        build:
            context: ./prod
            dockerfile: Prod.Dockerfile
        ports:
            - '8181:8080'
        links:
          - 'deploy'
        volumes:
          - /home/devops_learning/employment_7/tmp:/usr/local/tomcat/webapps

