---
version: '3'
services:
    deploy:
        build:
            context: ./deploy
            dockerfile: Deploy.Dockerfile
        volumes:
            - /home/tmp:/tmp
        command: sh -c "cp /home/java-war-project/target/war-app/my-app.war /tmp"
    prod:
        build:
            context: ./prod
            dockerfile: Prod.Dockerfile
        ports:
            - '8181:8080'
        links:
          - 'deploy'
        volumes:
          - /home/tmp:/usr/local/tomcat/webapps/
