---
version: '3'
services:
    deploy:
        build:
            context: ./deploy
            dockerfile: Deploy.Dockerfile
        volumes:
            - shared_volume:/shared_data
    prod:
        build:
            context: ./prod
            dockerfile: Prod.Dockerfile
        ports:
            - '8181:8080'
        links:
          - 'deploy'
        volumes:
          - shared_volume:/shared_data
volumes:
  shared_volume:
