---
version: '3'
services:
    deploy:
        build:
            context: ./deploy
            dockerfile: Deploy.Dockerfile
        volumes:
            - myapp:/app/java-war-project/target
    prod:
        build:
            context: ./prod
            dockerfile: Prod.Dockerfile
        ports:
            - '8181:8080'
        links:
          - 'deploy'
        depends_on:
          - deploy
        volumes:
          - myapp:/usr/local/tomcat/webapps
volumes:
    myapp:
