---
version: '3'
services:
    deploy:
        build:
            context: ./docker
            dockerfile: Deploy.Dockerfile
        volumes:
            - './tmp:/tmp/java-war-project/target'
        depends_on:
            - mariadb
    prod:
        build:
            context: ./docker
            dockerfile: Prod.Dockerfile
        ports:
            - '8181:8080'
        links:
          - 'deploy'
        volumes:
          - './tmp:/tmp/java-war-project/target'
